name: Cleanup action caches

permissions:
  actions: write

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      name:
        description: Which branch to use?
        default: main

jobs:
  cleanup:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 🧹 Clear unnecessary caches
        run: |
          gh extension install actions/gh-actions-cache

          # Setting this to not fail the workflow while deleting cache keys.
          set +e

          function get_branch() {
            local branch

            branch="${{ github.event.inputs.name }}"

            if [ "$branch" == "main" ]; then
              echo "main"
            else
              echo "refs/pull/${{ github.event.pull_request.number }}/merge"
            fi
          }

          function delete_caches() {
            local branch
            local cache_keys_for_pr
            local repo="${{ github.repository }}"

            branch=$(get_branch)

            if [ "$branch" == "main" ]; then
              echo "Fetching list of cache key on main except the last used"

              cache_keys_for_pr=$(gh actions-cache list -R "$repo" -B "$branch" | cut -f 1 | tail -n +2)
            else
              echo "Fetching list of cache key on refs/pull/..."

              cache_keys_for_pr=$(gh actions-cache list -R "$repo" -B "$branch" | cut -f 1)
            fi

            echo "Deleting caches..."

            for cache_key in $cache_keys_for_pr; do
              gh actions-cache delete "$cache_key" --repo "$repo" --branch "$branch" --confirm
            done

            echo "Done"
          }

          delete_caches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
